//
//  MockTest.swift
//  coursesApp
//
//  Created by Amit Levinzon on 06/07/2021.
//

import SwiftUI

struct MockTest: Identifiable{
    let id =  UUID()
    let imageName: String
    let title: String
    let description: String
    let sellPrice: String
    let originalPrice: String
    let Url: URL
}

struct MockTestList {
    static let LCOTest = [
        MockTest(imageName: "c-1", title: "Edition 1", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pretium quam vulputate dignissim suspendisse. Nisl vel pretium lectus quam id leo. Tortor posuere ac ut consequat semper viverra. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Blandit libero volutpat sed cras ornare arcu. Vulputate dignissim suspendisse in est ante in nibh mauris. Consectetur a erat nam at lectus urna duis convallis. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Ullamcorper a lacus vestibulum sed arcu non.", sellPrice: "199", originalPrice: "2999", Url: URL(string: "https://127.0.0.1/learn")!),
        MockTest(imageName: "c-2", title: "Edition 2", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pretium quam vulputate dignissim suspendisse. Nisl vel pretium lectus quam id leo. Tortor posuere ac ut consequat semper viverra. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Blandit libero volutpat sed cras ornare arcu. Vulputate dignissim suspendisse in est ante in nibh mauris. Consectetur a erat nam at lectus urna duis convallis. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Ullamcorper a lacus vestibulum sed arcu non.", sellPrice: "59", originalPrice: "2999", Url: URL(string: "https://127.0.0.1/learn")!),
        MockTest(imageName: "c-3", title: "Edition 3", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pretium quam vulputate dignissim suspendisse. Nisl vel pretium lectus quam id leo. Tortor posuere ac ut consequat semper viverra. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Blandit libero volutpat sed cras ornare arcu. Vulputate dignissim suspendisse in est ante in nibh mauris. Consectetur a erat nam at lectus urna duis convallis. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Ullamcorper a lacus vestibulum sed arcu non.", sellPrice: "299", originalPrice: "2999", Url: URL(string: "https://127.0.0.1/learn")!),
        MockTest(imageName: "c-4", title: "Edition 4", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pretium quam vulputate dignissim suspendisse. Nisl vel pretium lectus quam id leo. Tortor posuere ac ut consequat semper viverra. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Blandit libero volutpat sed cras ornare arcu. Vulputate dignissim suspendisse in est ante in nibh mauris. Consectetur a erat nam at lectus urna duis convallis. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Ullamcorper a lacus vestibulum sed arcu non.", sellPrice: "799", originalPrice: "2999", Url: URL(string: "https://127.0.0.1/learn")!),
        MockTest(imageName: "c-5", title: "Edition 5", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pretium quam vulputate dignissim suspendisse. Nisl vel pretium lectus quam id leo. Tortor posuere ac ut consequat semper viverra. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Blandit libero volutpat sed cras ornare arcu. Vulputate dignissim suspendisse in est ante in nibh mauris. Consectetur a erat nam at lectus urna duis convallis. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Ullamcorper a lacus vestibulum sed arcu non.", sellPrice: "1999", originalPrice: "2999", Url: URL(string: "https://127.0.0.1/learn")!),
        MockTest(imageName: "c-6", title: "Edition 6", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pretium quam vulputate dignissim suspendisse. Nisl vel pretium lectus quam id leo. Tortor posuere ac ut consequat semper viverra. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Blandit libero volutpat sed cras ornare arcu. Vulputate dignissim suspendisse in est ante in nibh mauris. Consectetur a erat nam at lectus urna duis convallis. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Ullamcorper a lacus vestibulum sed arcu non.", sellPrice: "9", originalPrice: "2999", Url: URL(string: "https://127.0.0.1/learn")!),
        MockTest(imageName: "c-7", title: "Edition 7", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pretium quam vulputate dignissim suspendisse. Nisl vel pretium lectus quam id leo. Tortor posuere ac ut consequat semper viverra. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Blandit libero volutpat sed cras ornare arcu. Vulputate dignissim suspendisse in est ante in nibh mauris. Consectetur a erat nam at lectus urna duis convallis. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Ullamcorper a lacus vestibulum sed arcu non.", sellPrice: "99", originalPrice: "2999", Url: URL(string: "https://127.0.0.1/learn")!),
        MockTest(imageName: "c-8", title: "Edition 8", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pretium quam vulputate dignissim suspendisse. Nisl vel pretium lectus quam id leo. Tortor posuere ac ut consequat semper viverra. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Blandit libero volutpat sed cras ornare arcu. Vulputate dignissim suspendisse in est ante in nibh mauris. Consectetur a erat nam at lectus urna duis convallis. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Ullamcorper a lacus vestibulum sed arcu non.", sellPrice: "39", originalPrice: "2999", Url: URL(string: "https://127.0.0.1/learn")!),
        MockTest(imageName: "c-9", title: "Edition 9", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pretium quam vulputate dignissim suspendisse. Nisl vel pretium lectus quam id leo. Tortor posuere ac ut consequat semper viverra. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Blandit libero volutpat sed cras ornare arcu. Vulputate dignissim suspendisse in est ante in nibh mauris. Consectetur a erat nam at lectus urna duis convallis. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Ullamcorper a lacus vestibulum sed arcu non.", sellPrice: "3999", originalPrice: "2999", Url: URL(string: "https://127.0.0.1/learn")!),
        MockTest(imageName: "c-10", title: "Edition 10", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pretium quam vulputate dignissim suspendisse. Nisl vel pretium lectus quam id leo. Tortor posuere ac ut consequat semper viverra. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Blandit libero volutpat sed cras ornare arcu. Vulputate dignissim suspendisse in est ante in nibh mauris. Consectetur a erat nam at lectus urna duis convallis. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Ullamcorper a lacus vestibulum sed arcu non.", sellPrice: "499", originalPrice: "2999", Url: URL(string: "https://127.0.0.1/learn")!),
    ]
}
